org.gradle.jvmargs=-Xmx4g -Dfile.encoding=UTF-8
org.gradle.caching=true
org.gradle.configuration-cache=true
kotlin.code.style=official
android.useAndroidX=true

# Publishing (com.vanniktech.maven.publish)
GROUP=io.github.skules777
VERSION_NAME=1.0.0
POM_INCEPTION_YEAR=2026
POM_URL=https://github.com/skules777/nbu-qr-code-kotlin
POM_SCM_URL=https://github.com/skules777/nbu-qr-code-kotlin
POM_SCM_CONNECTION=scm:git:git://github.com/skules777/nbu-qr-code-kotlin.git
POM_SCM_DEV_CONNECTION=scm:git:ssh://git@github.com/skules777/nbu-qr-code-kotlin.git
POM_LICENSE_NAME=MIT License
POM_LICENSE_URL=https://opensource.org/licenses/MIT
POM_LICENSE_DIST=repo
POM_DEVELOPER_ID=skules777
POM_DEVELOPER_NAME=Oleksandr Havrylenko
POM_DEVELOPER_URL=https://github.com/skules777
